using System;
using System.IO;
using System.Linq;

namespace ArmoSystems.ArmoGet.DeviceSettingsParser
{
    internal static class Program
    {
        private const string DirAutogeneratedDeviceInfo = @"D:\Temp\TimexTemp\Autogenerated\DevicesInfo";

        private static void ClearAutogeneratedDeviceInfoDir()
        {
            if ( Directory.Exists( DirAutogeneratedDeviceInfo ) )
                Directory.GetFiles( DirAutogeneratedDeviceInfo ).ToList().ForEach( File.Delete );
            else
                Directory.CreateDirectory( DirAutogeneratedDeviceInfo );
        }

        [STAThread]
        private static int Main( string[] args )
        {
            if ( args.Count() < 2 )
                return -2;
            var deviceSettingsParser = new DeviceSettingsOperator( args[ 0 ] );

            var res = deviceSettingsParser.ManageFile();
            if ( !res )
                return -1;
            deviceSettingsParser.CreateFile( $@"{args[ 1 ]}\Common\Database\TimexDatabaseDevices.cs" );
            deviceSettingsParser.CreateFileTerminalEnums( $@"{args[ 1 ]}\Shared\XPO\Source\Devices\DeviceTypeInfo1Generated.cs" );
            deviceSettingsParser.CreateFileDeviceTypeInfo( $@"{args[ 1 ]}\Shared\XPO\Source\Devices\DeviceTypeInfo1XPO.cs" );

            ClearAutogeneratedDeviceInfoDir();
            deviceSettingsParser.CreateAutogeneratedDevicesInfo( DirAutogeneratedDeviceInfo );
            return 0;
        }
    }
}